- hosts: all
  tasks:

  - name: Install nginx
    become: yes
    apt: name=nginx state=present update_cache=yes cache_valid_time=86400

  - name: Install fcgiwrap
    become: yes
    apt: name=fcgiwrap state=present update_cache=yes cache_valid_time=86400

  - name: Copy nginx configuration 
    become: yes
    template: src=default dest=/etc/nginx/sites-available/default

  - name: create cgi-bin directory
    become: yes
    file: path=/var/www/cgi-bin/ state=directory

  - name: restart nginx
    become: yes
    service: name=nginx state=restarted
